
export const CATEGORY_CLASS='CATEGORY_CLASS';
export const CATEGORY_SUB_TYPE_PRODUCT='CATEGORY_SUB_TYPE_PRODUCT';


export const QUERY_USER_INFO='QUERY_USER_INFO';

export const PERSONAL_QUERY_BASE = "PERSONAL_QUERY_BASE";

<<<<<<< HEAD
export const QUERY_SHOP_CART='QUERY_SHOP_CART';

=======




export const SHOP_CART_UNPAY='SHOP_CART_UNPAY';

export const SHOP_CART_PAY='SHOP_CART_PAY';


>>>>>>> 7eaadffbdfa394dc6d08fd46c9071c33a99f572b
