
export const QUERY_USER_INFO='QUERY_USER_INFO';

export const PERSONAL_QUERY_BASE = "PERSONAL_QUERY_BASE";

export const SHOP_CART_UNPAY='SHOP_CART_UNPAY';

export const SHOP_CART_PAY='SHOP_CART_PAY';