
export const CATEGORY_CLASS='CATEGORY_CLASS';
export const CATEGORY_SUB_TYPE_PRODUCT='CATEGORY_SUB_TYPE_PRODUCT';


export const QUERY_USER_INFO='QUERY_USER_INFO';

export const PERSONAL_QUERY_BASE = "PERSONAL_QUERY_BASE";


export const QUERY_SHOP_CART='QUERY_SHOP_CART';





export const SHOP_CART_UNPAY='SHOP_CART_UNPAY';

export const SHOP_CART_PAY='SHOP_CART_PAY';


/*home信息*/

export const HOME_QUERY_TOPCATEGORY='HOME_QUERY_TOPCATEGORY';

export const HOME_QUERY_BANNER='HOME_QUERY_BANNER';

export const HOME_QUERY_KILLPRODUCT='HOME_QUERY_KILLPRODUCT';

export const HOME_QUERY_FILTERPRODUCT='HOME_QUERY_FILTERPRODUCT';

/*商品详情*/
export const DETAIL_QUERY_PRODUCT = 'DETAIL_QUERY_PRODUCT';

